---
- name: Add Moby Apt key
  become: true
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Create Moby sources file
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://packages.microsoft.com/ubuntu/20.04/prod focal main
    state: present
    filename: 'microsoft-moby'
    update_cache: true

- name: Install Moby
  become: true
  apt:
    pkg:
      - moby-cli
      - moby-buildx
      - moby-compose
      - moby-engine
    state: present

- name: Ensure docker group exists
  ansible.builtin.group:
    name: docker
    state: present

- name: adding existing user '{{ local_user_username }}' to group docker
  user:
    name: '{{ local_user_username }}'
    groups: docker
    append: yes

