---
- name: Add Moby Apt key
  become: true
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Create Moby sources file
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://packages.microsoft.com/ubuntu/20.04/prod focal main
    state: present
    filename: 'microsoft-moby'
    update_cache: true

- name: Install Moby
  become: true
  apt:
    pkg:
      - moby-cli
      - moby-buildx
      - moby-compose
      - moby-engine
    state: present

- name: Ensure docker group exists
  become: true
  ansible.builtin.group:
    name: docker
    state: present

- name: adding existing user '{{ local_user_username }}' to group docker
  become: true
  user:
    name: '{{ local_user_username }}'
    groups: docker
    append: yes

- name: Install init script for Moby
  become: true
  get_url:
    url: https://raw.githubusercontent.com/moby/moby/master/contrib/init/sysvinit-debian/docker
    dest: /etc/init.d/docker
    owner: root
    group: root
    mode: 755

